#######################
# Theme Customization #
#######################

title: Ryan Lue
author: Ryan Lue
description: Just another software developer’s personal blog.
slogan: Just my 2¢
avatar: /i/avatar.png
banner: /i/mountains.svg
url: https://ryanlue.com
baseurl: ''
repo: https://github.com/rlue/rlue.github.io

nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/rlue/
    icon: /i/icons.svg#github
    outbound: true
  - name: Contact
    scheme: mailto
    handle: hello
    domain: ryanlue.com
    icon: /i/icons.svg#email

projects:
  - title: Timer
    teaser: A command-line pomodoro/interval timer
    url: https://github.com/rlue/timer
    role: Owner
    category: CLI Utility
  - title: Barbaric
    teaser: Automatic input method switching for vim
    url: https://github.com/rlue/vim-barbaric
    role: Owner
    category: Vim Plugin
  - title: Nelson Scandela
    teaser: A barebones barcode generator
    url: https://github.com/rlue/nelson-scandela
    role: Owner
    category: Toy App (Sinatra)
  - title: xferase
    teaser: Always-on, fully-automated photo import utility
    url: https://github.com/rlue/xferase
    role: Owner
    category: CLI Utility
  - title: Cram
    teaser: A toolkit for automating Anki flashcard creation
    url: https://github.com/rlue/cram
    role: Owner
    category: CLI Utility

#################
# Site Settings #
#################

incremental: true
exclude:
  - LICENSE
  - README.md
  - TODO.md
  - tags
include:
  - .well-known

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
