#######################
# Theme Customization #
#######################

title: Ryan Lue
author: Ryan Lue
description: Just another software developer’s personal blog.
slogan: Just my 2¢
avatar: /i/avatar.png
banner: /i/mountains.svg
url: https://ryanlue.com
baseurl: ''
repo: https://github.com/rlue/rlue.github.io

nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/rlue/
    icon: /i/icons.svg#github
    outbound: true
  - name: Contact
    scheme: mailto
    handle: hello
    domain: ryanlue.com
    icon: /i/icons.svg#email

projects:
  - title: Bodega
    teaser: A supply chain management tool for wholesalers.
    url: https://bodega.ryanlue.com/
    role: Creator
    category: Rails App
  - title: Getting Things Down
    teaser: Outlining and TODO shortcuts for GTD in plain ol' Markdown.
    url: https://github.com/rlue/vim-getting-things-down
    role: Creator
    category: Vim Plugin
  - title: Solana
    teaser: The theme for this site. A responsive template written in vanilla Sass and JavaScript.
    url: https://github.com/rlue/jekyll-solana
    role: Creator
    category: Frontend Dev
  - title: Something Like That
    teaser: A Ruby library for fuzzy string matching of long, multi-word phrases.
    url: https://github.com/rlue/something_like_that
    role: Creator
    category: Gems
  - title: Timer
    teaser: A command-line pomodoro/interval timer.
    url: https://github.com/rlue/timer
    role: Creator
    category: Bash Scripts

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md
  - tags
include:
  - .well-known

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
