#######################
# Theme Customization #
#######################

title: Ryan Lue
author: Ryan Lue
description: Just another software developer’s personal blog.
slogan: Just my 2¢
avatar: /i/avatar.png
banner: /i/mountains.svg
url: https://ryanlue.com
baseurl: ''
repo: https://github.com/rlue/rlue.github.io

nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/rlue/
    icon: /i/icons.svg#github
    outbound: true
  - name: Contact
    scheme: mailto
    handle: hello
    domain: ryanlue.com
    icon: /i/icons.svg#email

projects:
  - title: Nelson Scandela
    teaser: A barebones barcode generator.
    url: https://github.com/rlue/nelson-scandela
    role: Owner
    category: Toy App (Sinatra)
  - title: Marshmallows
    teaser: An interest calculator, with authentication and a JSON API.
    url: https://desolate-brushlands-25174.herokuapp.com/
    role: Owner
    category: Toy App (Rails)
  - title: Solana
    teaser: The theme for this site. A responsive template written in vanilla Sass and JavaScript.
    url: https://github.com/rlue/jekyll-solana
    role: Owner
    category: CSS/Design
  - title: Timer
    teaser: A command-line pomodoro/interval timer.
    url: https://github.com/rlue/timer
    role: Owner
    category: Bash Scripts
  - title: Getting Things Down
    teaser: Outlining and TODO shortcuts for GTD in plain ol' Markdown.
    url: https://github.com/rlue/vim-getting-things-down
    role: Owner
    category: Vim Plugin
  - title: Barbaric
    teaser: Automatic input method switching for vim.
    url: https://github.com/rlue/vim-barbaric
    role: Owner
    category: Vim Plugin

#################
# Site Settings #
#################

incremental: true
exclude:
  - LICENSE
  - README.md
  - TODO.md
  - tags
include:
  - .well-known

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
